name = "ClimaUtilities"
uuid = "b3f4f4ca-9299-4f7f-bd9b-81e1242a7513"
authors = ["Gabriele Bozzola <gbozzola@caltech.edu>", "Julia Sloan <jsloan@caltech.edu>"]
version = "0.1.2"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
ClimaCoreTempestRemap = "d934ef94-cdd4-4710-83d6-720549644b70"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
ClimaArtifactsExt = ["ClimaComms"]
DataHandlingExt = ["ClimaCore", "NCDatasets"]
InterpolationsRegridderExt = ["Interpolations", "ClimaCore"]
NCFileReaderExt = "NCDatasets"
SpaceVaryingInputsAnalyticExt = "ClimaCore"
SpaceVaryingInputsExt = ["ClimaCore", "NCDatasets"]
TempestRegridderExt = "ClimaCoreTempestRemap"
TimeVaryingInputs0DExt = "ClimaCore"
TimeVaryingInputsAnalyticExt = ["ClimaCore", "NCDatasets"]
TimeVaryingInputsExt = ["ClimaCore", "NCDatasets"]

[compat]
Adapt = "3, 4"
Artifacts = "1"
CFTime = "0.1"
ClimaComms = "0.5"
ClimaCore = "0.11, 0.12, 0.13"
ClimaCoreTempestRemap = "0.3"
Dates = "1"
Interpolations = "0.15"
NCDatasets = "0.13, 0.14"
julia = "1.9"
