name = "ClimaUtilities"
uuid = "b3f4f4ca-9299-4f7f-bd9b-81e1242a7513"
authors = ["Gabriele Bozzola <gbozzola@caltech.edu>", "Julia Sloan <jsloan@caltech.edu>"]
version = "0.1.8"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
ClimaCoreTempestRemap = "d934ef94-cdd4-4710-83d6-720549644b70"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
CUDAUtilsExt = ["ClimaCore", "CUDA"]
DataHandlingExt = ["ClimaCore", "NCDatasets"]
InterpolationsRegridderExt = ["Interpolations", "ClimaCore"]
MPIUtilsExt = "ClimaComms"
NCFileReaderExt = "NCDatasets"
SpaceVaryingInputsExt = ["ClimaCore", "NCDatasets"]
TempestRegridderExt = "ClimaCoreTempestRemap"
TimeVaryingInputs0DExt = "ClimaCore"
TimeVaryingInputsExt = ["ClimaCore", "NCDatasets"]

[compat]
Adapt = "3.3, 4"
Artifacts = "1"
ClimaComms = "0.5.6, 0.6"
ClimaCore = "0.12, 0.13, 0.14"
ClimaCoreTempestRemap = "0.3.13"
CUDA = "5"
Dates = "1"
Interpolations = "0.15"
NCDatasets = "0.13.1, 0.14"
julia = "1.9"
