agents:
  slurm_mem: 8G
  modules: climacommon/2024_04_05

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  SLURM_KILL_BAD_EXIT: 1

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project=test -e 'using Pkg; Pkg.develop(; path = \".\")'"
      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_cpus_per_task: 8
      slurm_gpus: 1

  - wait

  - label: "Run tests on CPU"
    key: "cpu_tests"
    command:
      - "julia --project=test test/runtests.jl"

  - label: "Run tests on GPU"
    key: "gpu_tests"
    command:
      - "julia --project=test test/runtests.jl"
    agents:
      slurm_gpus: 1

  - label: "Run tests with MPI"
    key: "mpi_tests"
    command:
      - "julia --project=test test/runtests.jl"
    agents:
      slurm_cpus_per_task: 2
