name: Downstream
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: downstream ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - 'ClimaAtmos.jl'
          - 'ClimaLand.jl'
          - 'ClimaCoupler.jl'
        version:
          - '1.10'
          - '1.11'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: actions/checkout@v4
        with:
          repository: 'CliMA/${{ matrix.package }}'
          path: ${{ matrix.package }}
      - if: matrix.package != 'ClimaCoupler.jl'
        run: |
          julia --color=yes --project=${{ matrix.package }} -e 'using Pkg; Pkg.instantiate()'
          julia --color=yes --project=${{ matrix.package }} -e 'using Pkg; Pkg.develop(; path = ".")'
          julia --color=yes --project=${{ matrix.package }} -e 'using Pkg; Pkg.test()'

      - if: matrix.package == 'ClimaCoupler.jl'
        run: |
          julia --color=yes --project=ClimaCoupler.jl/experiments/ClimaEarth -e 'using Pkg; Pkg.instantiate()'
          julia --color=yes --project=ClimaCoupler.jl/experiments/ClimaEarth -e 'using Pkg; Pkg.develop(; path = ".")'
          julia --color=yes --project=ClimaCoupler.jl/experiments/ClimaEarth ClimaCoupler.jl/experiments/ClimaEarth/test/runtests.jl
