name: JuliaFormatter

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v5

    - uses: dorny/paths-filter@v3.0.2
      id: filter
      with:
        filters: |
          julia_file_change:
            - added|modified: '**.jl'
    - uses: julia-actions/setup-julia@latest
      if: steps.filter.outputs.julia_file_change == 'true'
      with:
        version: "1.10"

    - uses: julia-actions/cache@v2
      if: steps.filter.outputs.julia_file_change == 'true'

    - name: Apply JuliaFormatter
      if: steps.filter.outputs.julia_file_change == 'true'
      run: |
        julia -e 'using Pkg; Pkg.add("JuliaFormatter"); using JuliaFormatter; format(".")'

    - name: Check formatting diff
      if: steps.filter.outputs.julia_file_change == 'true'
      run: |
        git diff --color=always --exit-code
